### ISSUE TITLE
Extension readiness

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#1411]
- [x] does manifest v2 still work (https://github.com/oasisprotocol/oasis-wallet-web/issues/1168)
- [x] does ledger work
- [x] enable paratimes
- [x] do we need a Chinese translation
  - [x] migrate selected language
- [x] will camera in transak iframe work for KYC
- [x] migrate old storage and warn users about not storing mnemonic anymore (https://github.com/oasisprotocol/oasis-wallet-web/issues/792#issuecomment-1269273318)
- [ ] do we need notifications
- [ ] do we need dapp support https://github.com/oasisprotocol/oasis-wallet-web/issues/786
